const ActionTypes = {
  FETCH_GLOBAL_CASES_SUCCESS: 'FETCH_GLOBAL_CASES_SUCCESS',
  FETCH_LIST_SUCCESS: 'FETCH_LIST_SUCCESS',
  FETCH_GRAPH_SUCCESS: 'FETCH_GRAPH_SUCCESS',
};

export default ActionTypes;
